# ("keyword"): ("image_name", "title"),
IMAGE_MAP = {
    ("aalesund", "ålesund"): ("alesund.png", "Brann - Aalesund"),
    ("bodø",): ("bodoglimt.png", "Brann - Bodø/Glimt"),
    ("fredrikstad",): ("fredrikstad.png", "Brann - Fredrikstad"),
    ("hamkam", "hamar"): ("hamkam.png", "Brann - HamKam"),
    ("haugesund",): ("haugesund.png", "Brann - Haugesund"),
    ("kfum",): ("kfum.png", "Brann - KFUM Oslo"),
    ("kristiansund",): ("kristiansund.png", "Brann - Kristiansund"),
    ("lillestrøm",): ("lillestrom.png", "Brann - Lillestrøm"),
    ("molde",): ("molde.png", "Brann - Molde"),
    ("odd",): ("odd.png", "Brann - Odd"),
    ("rosenborg",): ("rosenborg.png", "Brann - Rosenborg"),
    ("sandefjord",): ("sandefjord.png", "Brann - Sandefjord"),
    ("sarpsborg",): ("sarpsborg.png", "Brann - Sarpsborg"),
    ("stabæk",): ("stabek.png", "Brann - Stabæk"),
    ("strømsgodset",): ("stromsgodset.png", "Brann - Strømsgodset"),
    ("tromsø",): ("tromso.png", "Brann - Tromsø"),
    ("vålerenga",): ("valrenga.png", "Brann - Vålerenga"),
    ("viking",): ("viking.png", "Brann - Viking"),
    ("alkmaar",): ("alkmaar.png", "Brann - AZ Alkmaar"),
    ("glasgow",): ("default.png", "UEFA CL Runde 2: Brann - Glasgow City"),
    ("praha",): ("default.png", "UEFA CL Group B: Brann - Slavia Praha"),
    ("lyon",): ("lyon.png", "UEFA CL Group B: Brann - Lyon"),
    ("pölten",): ("polten.png", "UEFA CL Group B: Brann - St. Pölten"),
    ("barcelona",): ("barcelona_femini.png", "UEFA CL Kvartfinale: Brann - Barcelona"),
    ("partoutkort eliteserien",): ("eliteserien_logo.png", "\nPartoutkort Eliteserien 2024"),
    ("partoutkort toppserien",): ("toppserien_logo.png", "\nPartoutkort Toppserien 2024"),
}
